#!/usr/bin/python2

import sys
import os
from pathlib import Path
import commands

def showfunc(fil):
	if os.path.isfile(fil)==True:
		f1=open(fil,'r+')
		data=f1.read()
		f1.close()

		if data=='':
			exit
		else:
			
			#term=commands.getoutput("tty")	
			#print term
			print data

	elif os.path.isdir(fil)==True:
		print fil+' is a directory'

	else:
		print 'No such file or directory.' 


arg=sys.argv[1:]

for i in arg:
	showfunc(i)

